### PR TITLE
generate_automaton_to_file: add overwrite_existing argument

### PR DESCRIPTION
**Pull request by rominf**

### CODE REVIEW

**Comment by antoinewdg** [comment]
Hi @rominf , thanks for your interest in this repo.
This is really more a toy project than a real lib (it works though), so I think it would be much simpler for you to just fork it rather than publish a PR and wait for my validation :)

**Comment by rominf** [comment]
@antoinewdg it's too good for a toy project :)
OK, then. Do you mind if I publish it under the name `pyffs` at PyPI?

**Comment by antoinewdg** [comment]
@rominf, sure no problem :)
Out of curiosity, what are you using it for ?

**Comment by rominf** [comment]
@antoinewdg, I'm using it in profanity filter (https://github.com/rominf/profanityfilter) to find the closest similar profane word to the current word (https://github.com/rominf/profanityfilter/blob/master/profanityfilter/profanityfilter.py#L282).

**Pull request closed without merging**
